PUT http://localhost:6384/api/v1/session
Content-Type: application/json

{
  "scenario_id": "001",
  "state": "TEAM_NAMING"
}

###
POST http://localhost:6384/api/v1/teams
Content-Type: application/json

{
  "name": "foo the bar"
}

###
POST http://localhost:6384/api/v1/teams
Content-Type: application/json

{
  "name": "Bar baz"
}

###
POST http://localhost:6384/api/v1/teams
Content-Type: application/json

{
  "name": "Team 3"
}

###
POST http://localhost:6384/api/v1/teams
Content-Type: application/json

{
  "name": "Team 400"
}

###
PUT http://localhost:6384/api/v1/session
Content-Type: application/json

{
  "scenario_id": "001",
  "state": "SCANNING"
}